version: "3.8"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
  etherpad:
    image: etherpad/etherpad
    ports:
      - "9001:9001"
    volumes:
      - ./api/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25" 

  quarkus:
    build:
      context: ./api
      dockerfile: src/main/docker/Dockerfile.native
    depends_on:
      - db
    restart: always

  angular:
    build: "./front"
    container_name: angular
    ports: 
      - "8080:80"
    depends_on:
      - quarkus

