name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Quarkus Docker image
      run: |
        ls
        docker build -t legel/doodlestudent-quarkus:latest ./api/src/main/docker/Dockerfile.jvm
        docker push legel/doodlestudent-quarkus:latest

    - name: Build and push Proxy Docker image
      run: |
        docker build -t legel/doodlestudent-proxy:latest .
        docker push legel/doodlestudent-proxy:latest

    - name: Build and push Angular Docker image
      run: |
        docker build -t legel/doodlestudent-angular:latest ./front
        docker push legel/doodlestudent-angular:latest
