name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Check content of target/quarkus-app
      run: |
        cd api
        ./mvnw clean package
        ls -l target/quarkus-app

    - name: Build and push Quarkus Docker image
      run: |
        docker build -t legel/doodlestudent-quarkus:latest api
        docker push legel/doodlestudent-quarkus:latest

    - name: Build and push Proxy Docker image
      run: |
        docker build -t legel/doodlestudent-proxy:latest .
        docker push legel/doodlestudent-proxy:latest

    - name: Build and push Angular Docker image
      run: |
        docker build -t legel/doodlestudent-angular:latest ./front
        docker push legel/doodlestudent-angular:latest
